import { collection, getDocs, writeBatch, doc } from 'firebase/firestore';
import { db } from '../lib/firebase';

const rawTable = `ASIGNATURA\tSUBNIVEL\tCODIGO_CE\tCRITERIO_EVALUACION\tCODIGO_DCD\tDESTREZA_DCD\tCODIGO_IE\tINDICADOR_EVALUACION\tCOMPETENCIAS\tINSERCIONES\tDESAGREGADA
Lengua y Literatura\tEGB Superior\tCE.LL.4.1.\tCE.LL.4.1. Explica los aportes de la cultura escrita al desarrollo histórico, social y cultural de la humanidad y valora la diversidad del mundo expresada en textos escritos representativos de las diferentes culturas, en diversas épocas históricas.[cite: 17]\tLL.4.1.1.\tLL.4.1.1. Indagar y explicar los aportes de la cultura escrita al desarrollo histórico, social y cultural de la humanidad.[cite: 17]\tI.LL.4.1.1.\tI.LL.4.1.1. Explica el origen, el desarrollo y la influencia de la escritura en distintos momentos históricos, regiones y culturas del mundo, y valora la diversidad expresada en sus textos representativos. (S.2., I.3.)[cite: 17]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.1.\tCE.LL.4.1. Explica los aportes de la cultura escrita al desarrollo histórico, social y cultural de la humanidad y valora la diversidad del mundo expresada en textos escritos representativos de las diferentes culturas, en diversas épocas históricas.[cite: 17]\tLL.4.1.2.\tLL.4.1.2. Valorar la diversidad cultural del mundo expresada en textos.[cite: 17]\tI.LL.4.1.1.\tI.LL.4.1.1. Explica el origen, el desarrollo y la influencia de la escritura en distintos momentos históricos, regiones y culturas del mundo, y valora la diversidad expresada en sus textos representativos. (S.2., I.3.)[cite: 17]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.2.\tCE.LL.4.2. Explica la influencia de las variaciones lingüísticas socioculturales y situacionales del Ecuador en las relaciones sociales, así como la correspondencia entre la estructura de la lengua y las formas de pensar y actuar de las personas.[cite: 17]\tLL.4.1.3.\tLL.4.1.3. Indagar sobre las variaciones lingüísticas socioculturales del Ecuador y explicar su influencia en las relaciones sociales.[cite: 17]\tRef.I.LL.4.2.1.\tExplica la influencia de las variaciones lingüísticas sociales y situacionales del Ecuador en las relaciones sociales. (Ref.I.LL.4.2.1.) (I.3.,S.3)[cite: 17]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.3.\tCE.LL.4.3. Valora el contenido explícito de dos o más textos orales, identificando contradicciones, ambigüedades, falacias, distorsiones, desviaciones en el discurso; y reflexiona sobre los efectos del uso de estereotipos y prejuicios en la comunicación.[cite: 17]\tLL.4.2.4.\tLL.4.2.4. Reflexionar sobre los efectos del uso de estereotipos y prejuicios en la comunicación.[cite: 17]\tRef.I.LL.4.3.1.\tReflexiona sobre los efectos de los estereotipos y prejuicios en la comunicación. (Ref. I.LL.4.3.1.) (J.3., I.4.)[cite: 17]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.4.\tCE.LL.4.4. Organiza sus discursos según las estructuras básicas de la lengua oral, utiliza un vocabulario acorde a la intención (construir acuerdos, solucionar problemas, etc.) y al contexto e integra una variedad de recursos, formatos y soportes, evaluando su impacto en la audiencia.[cite: 17]\tLL.4.2.1.\tLL.4.2.1. Utilizar recursos de la comunicación oral en contextos de intercambio social, construcción de acuerdos y resolución de problemas.[cite: 17]\tRef.I.LL.4.4.1.\tConstruye acuerdos, soluciona problemas y evalúa su impacto en la audiencia. (Ref. I.LL.4.4.1.) (J.3.,I3.)[cite: 17]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.4.\tCE.LL.4.4. Organiza sus discursos según las estructuras básicas de la lengua oral, utiliza un vocabulario acorde a la intención (construir acuerdos, solucionar problemas, etc.) y al contexto e integra una variedad de recursos, formatos y soportes, evaluando su impacto en la audiencia.[cite: 17]\tLL.4.2.2.\tLL.4.2.2. Organizar el discurso mediante el uso de las estructuras básicas de la lengua oral, la selección y empleo de vocabulario específico, acorde con la intencionalidad, en diversos contextos comunicativos formales e informales.[cite: 17]\tI.LL.4.4.2.\tI.LL.4.4.2. Produce discursos (conversación, diálogo, narración, debate, conversatorio, presentación, entrevista, encuesta, exposición) organizados a partir del uso de las estructuras básicas de la lengua oral, utiliza un vocabulario acorde a la intención y el contexto, los apoya con una variedad de formatos, soportes y recursos (incluyendo los audiovisuales.). (I.3., I.4.)[cite: 17]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.4.\tCE.LL.4.4. Organiza sus discursos según las estructuras básicas de la lengua oral, utiliza un vocabulario acorde a la intención (construir acuerdos, solucionar problemas, etc.) y al contexto e integra una variedad de recursos, formatos y soportes, evaluando su impacto en la audiencia.[cite: 17]\tLL.4.2.3.\tLL.4.2.3. Producir discursos que integren una variedad de recursos, formatos y soportes.[cite: 17]\tI.LL.4.4.2.\tI.LL.4.4.2. Produce discursos organizados a partir del uso de las estructuras básicas de la lengua oral... (I.3., I.4.)[cite: 17]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.5.\tCE.LL.4.5. Comprende en sus niveles literal, inferencial y crítico-valorativo diversos tipos de texto, al comparar bajo criterios preestablecidos las relaciones explícitas entre sus contenidos, inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto...[cite: 18]\tLL.4.3.1.\tLL.4.3.1. Comparar, bajo criterios preestablecidos, las relaciones explícitas entre los contenidos de dos o más textos y contrastar sus fuentes.[cite: 18]\tRef.I.LL.4.5.1.\tCompara, bajo criterios preestablecidos, las relaciones explícitas entre los contenidos de dos o más textos y contrasta sus fuentes; autorregula la comprensión mediante el uso de estrategias cognitivas... (Ref.I.LL.4.5.1.) (J.4.,I.4.)[cite: 18]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.5.\tCE.LL.4.5. Comprende en sus niveles literal, inferencial y crítico-valorativo diversos tipos de texto, al comparar bajo criterios preestablecidos las relaciones explícitas entre sus contenidos, inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto...[cite: 18]\tLL.4.3.2.\tLL.4.3.2. Construir significados implícitos al inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto.[cite: 18]\tRef.I.LL.4.5.2.\tConstruye significados implícitos al inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto y elabora criterios crítico-valorativos... (Ref. I.LL.4.5.2.) (J.2.,I.3)[cite: 18]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.5.\tCE.LL.4.5. Comprende en sus niveles literal, inferencial y crítico-valorativo diversos tipos de texto, al comparar bajo criterios preestablecidos las relaciones explícitas entre sus contenidos, inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto...[cite: 18]\tLL.4.3.3.\tLL.4.3.3. Elaborar criterios crítico-valorativos al distinguirlas diferentes perspectivas en conflicto sobre un mismo tema, en diferentes textos.[cite: 18]\tRef.I.LL.4.5.2.\tConstruye significados implícitos al inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto y elabora criterios crítico-valorativos... (Ref. I.LL.4.5.2.) (J.2.,I.3)[cite: 18]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.5.\tCE.LL.4.5. Comprende en sus niveles literal, inferencial y crítico-valorativo diversos tipos de texto, al comparar bajo criterios preestablecidos las relaciones explícitas entre sus contenidos, inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto...[cite: 18]\tLL.4.3.4.\tLL.4.3.4. Autorregular la comprensión de un texto mediante la aplicación de estrategias cognitivas de comprensión autoseleccionadas, de acuerdo con el propósito de lectura y las dificultades identificadas.[cite: 18]\tRef.I.LL.4.5.1.\tCompara, bajo criterios preestablecidos, las relaciones explícitas entre los contenidos de dos o más textos y contrasta sus fuentes; autorregula la comprensión... (Ref.I.LL.4.5.1.) (J.4.,I.4.)[cite: 18]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.5.\tCE.LL.4.5. Comprende en sus niveles literal, inferencial y crítico-valorativo diversos tipos de texto, al comparar bajo criterios preestablecidos las relaciones explícitas entre sus contenidos, inferir el tema, el punto de vista del autor, las motivaciones y argumentos de un texto...[cite: 18]\tLL.4.3.12.\tLL.4.3.12. Identificar las acciones básicas de asistencia en caso de siniestros de tránsito, mediante la revisión de protocolos de emergencia en fuentes oficiales.[cite: 18]\tI.LL.4.5.3.\tI.LL.4.5.3. Analiza protocolos de emergencia locales y nacionales para conocer la manera correcta de actuar en siniestros de tránsito. (J.2., I.1.)[cite: 18]\t\tSeguridad Integral\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.6.\tCE.LL.4.6. Consulta bibliotecas y recursos digitales en la web, comparándolos y valorándolos en función de la confiabilidad de la fuente, el propósito de la lectura y la calidad de la información, recogiéndola, contrastándola y organizándola en esquemas de diverso tipo.[cite: 18]\tLL.4.3.5.\tLL.4.3.5. Valorar y comparar textos de consulta en función del propósito de lectura y la calidad de la información (claridad, organización, actualización, amplitud, profundidad y otros).[cite: 18]\tI.LL.4.6.1.\tI.LL.4.6.1. Consulta bibliotecas y recursos digitales en la web, con capacidad para comparar y valorar textos en función del propósito de lectura, la calidad de la información y la confiabilidad de la fuente... (J.2.,I.4.)[cite: 18]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.6.\tCE.LL.4.6. Consulta bibliotecas y recursos digitales en la web, comparándolos y valorándolos en función de la confiabilidad de la fuente, el propósito de la lectura y la calidad de la información, recogiéndola, contrastándola y organizándola en esquemas de diverso tipo.[cite: 18]\tLL.4.3.6.\tLL.4.3.6. Consultar bibliotecas y recursos digitales en la web, con capacidad para analizar la confiabilidad de la fuente.[cite: 18]\tI.LL.4.6.1.\tI.LL.4.6.1. Consulta bibliotecas y recursos digitales en la web, con capacidad para comparar y valorar textos en función del propósito de lectura, la calidad de la información y la confiabilidad de la fuente... (J.2.,I.4.)[cite: 18]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.6.\tCE.LL.4.6. Consulta bibliotecas y recursos digitales en la web, comparándolos y valorándolos en función de la confiabilidad de la fuente, el propósito de la lectura y la calidad de la información, recogiéndola, contrastándola y organizándola en esquemas de diverso tipo.[cite: 18]\tLL.4.3.7.\tLL.4.3.7. Recoger, comparar y organizar información consultada en esquemas de diverso tipo.[cite: 18]\tI.LL.4.6.1.\tI.LL.4.6.1. Consulta bibliotecas y recursos digitales en la web, con capacidad para comparar y valorar textos en función del propósito de lectura, la calidad de la información y la confiabilidad de la fuente... (J.2.,I.4.)[cite: 18]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.6.\tCE.LL.4.6. Consulta bibliotecas y recursos digitales en la web, comparándolos y valorándolos en función de la confiabilidad de la fuente, el propósito de la lectura y la calidad de la información, recogiéndola, contrastándola y organizándola en esquemas de diverso tipo.[cite: 18]\tLL.4.3.10.\tLL.4.3.10. Consultar bases de datos digitales y otros recursos de la web, con capacidad para seleccionar fuentes según el propósito de lectura, y valorar la confiabilidad e interés o punto de vista de las fuentes escogidas.[cite: 19]\tI.LL.4.6.1.\tI.LL.4.6.1. Consulta bibliotecas y recursos digitales en la web, con capacidad para comparar y valorar textos en función del propósito de lectura, la calidad de la información y la confiabilidad de la fuente... (J.2.,I.4.)[cite: 18]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.6.\tCE.LL.4.6. Consulta bibliotecas y recursos digitales en la web, comparándolos y valorándolos en función de la confiabilidad de la fuente, el propósito de la lectura y la calidad de la información, recogiéndola, contrastándola y organizándola en esquemas de diverso tipo.[cite: 18]\tLL.4.3.11.\tLL.4.3.11. Consultar en bases de datos digitales y otros recursos de la web sobre las normas básicas de circulación de los peatones, ciclistas, motociclistas, conductores y personas con discapacidad; y analizar su importancia para la movilidad segura.[cite: 19]\tI.LL.4.6.1.\tI.LL.4.6.1. Consulta bibliotecas y recursos digitales en la web, con capacidad para comparar y valorar textos en función del propósito de lectura, la calidad de la información y la confiabilidad de la fuente... (J.2.,I.4.)[cite: 18]\t\tSeguridad Vial\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.1.\tLL.4.4.1. Escribir textos periodísticos y académicos con manejo de su estructura básica, y sustentar las ideas con razones y ejemplos organizados de manera jerárquica.[cite: 19]\tI.LL.4.7.1.\tI.LL.4.7.1. Estructura diferentes tipos de textos periodísticos y académicos, combinando diferentes tramas, tipos de párrafo y diálogos directos e indirectos, según sean pertinentes; maneja las normas de citación e identificación de fuentes más comunes... (J.2.,I.4)[cite: 19]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.2.\tLL.4.4.2. Lograr cohesión y coherencia en la escritura de textos periodísticos y académicos mediante la construcción y organización de diferentes tipos de párrafos.[cite: 19]\tI.LL.4.7.1.\tI.LL.4.7.1. Estructura diferentes tipos de textos periodísticos y académicos, combinando diferentes tramas, tipos de párrafo y diálogos directos e indirectos, según sean pertinentes; maneja las normas de citación e identificación de fuentes más comunes... (J.2.,I.4)[cite: 19]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.3.\tLL.4.4.3. Usar estrategias y procesos de pensamiento que apoyen la escritura de diferentes tipos de textos periodísticos y académicos.[cite: 19]\tI.LL.4.7.2.\tI.LL.4.7.2. Usa el procedimiento de producción de textos en la escritura de textos periodísticos y académicos y aplica estrategias que apoyen cada uno de sus pasos... maneja las normas de citación e identificación de fuentes más utilizadas (APA, Chicago y otras). (J.2., I.4.)[cite: 20]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.4.\tLL.4.4.4. Autorregular la escritura de textos periodísticos y académicos con la selección y aplicación de variadas técnicas y recursos.[cite: 19]\tI.LL.4.7.2.\tI.LL.4.7.2. Usa el procedimiento de producción de textos en la escritura de textos periodísticos y académicos y aplica estrategias que apoyen cada uno de sus pasos... maneja las normas de citación e identificación de fuentes más utilizadas (APA, Chicago y otras). (J.2., I.4.)[cite: 20]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.5.\tLL.4.4.5. Usar el procedimiento de planificación, redacción, revisión y publicación en la escritura de diferentes tipos de textos periodísticos y académicos.[cite: 19]\tI.LL.4.7.2.\tI.LL.4.7.2. Usa el procedimiento de producción de textos en la escritura de textos periodísticos y académicos y aplica estrategias que apoyen cada uno de sus pasos... maneja las normas de citación e identificación de fuentes más utilizadas (APA, Chicago y otras). (J.2., I.4.)[cite: 20]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.6.\tLL.4.4.6. Mejorar la claridad y precisión de diferentes tipos de textos periodísticos y académicos mediante la escritura de oraciones compuestas y la utilización de nexos, modificadores, objetos, complementos y signos de puntuación.[cite: 20]\tI.LL.4.7.3.\tI.LL.4.7.3. Utiliza elementos gramaticales en la producción de textos periodísticos y académicos... en función de mejorar la claridad y precisión y matizar las ideas y los significados de oraciones y párrafos. (I.3., I.4.)[cite: 20]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.7.\tCE.LL.4.7. Produce diferentes tipos de textos periodísticos (reportajes, crónicas, noticias, entrevistas, artículos de opinión, entre otros) y académicos (artículos y proyectos de investigación, informes, reseñas, resúmenes, ensayos) con coherencia y cohesión, autorregulando la escritura...[cite: 19]\tLL.4.4.7.\tLL.4.4.7. Matizar y precisar las ideas y los significados de oraciones y párrafos mediante el uso selectivo de modos verbales, tiempos verbales complejos, verboides, voz activa y pasiva, conjunciones y frases nominales, adjetivas, adverbiales, preposicionales y verbales.[cite: 20]\tI.LL.4.7.3.\tI.LL.4.7.3. Utiliza elementos gramaticales en la producción de textos periodísticos y académicos... en función de mejorar la claridad y precisión y matizar las ideas y los significados de oraciones y párrafos. (I.3., I.4.)[cite: 20]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.8.\tCE.LL.4.8. Lee textos literarios en función de sus preferencias personales, los interpreta y sustenta su interpretación al debatir críticamente sobre ella, basándose en indagaciones sobre el tema, género y contexto.[cite: 21]\tLL.4.5.1.\tLL.4.5.1. Interpretar un texto literario desde las características del género al que pertenece.[cite: 21]\tRef. I.LL.4.8.1.\tInterpreta textos literarios a partir de las características del género al que pertenecen. (Ref. I.LL.4.8.1.) (J.4.,S.4)[cite: 21]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.8.\tCE.LL.4.8. Lee textos literarios en función de sus preferencias personales, los interpreta y sustenta su interpretación al debatir críticamente sobre ella, basándose en indagaciones sobre el tema, género y contexto.[cite: 21]\tLL.4.5.3.\tLL.4.5.3. Elegir lecturas basándose en preferencias personales de autor, género, estilo, temas y contextos socioculturales, con el manejo de diversos soportes.[cite: 21]\tRef. I.LL.4.8.2.\tElige lecturas en función de sus preferencias personales de autor, género, estilo, temas y contextos socioculturales; maneja diversos soportes. (Ref. I.LL.4.8.2.) (J.4.,I.3.)[cite: 21]\t\t\tSI
Lengua y Literatura\tEGB Superior\tCE.LL.4.9.\tCE.LL.4.9. Compone y recrea textos literarios que adaptan o combinan diversas estructuras y recursos literarios, expresa intenciones determinadas (ironía, sarcasmo, humor, etc.) mediante el uso creativo del significado de las palabras, la utilización colaborativa de diversos medios y recursos de las TIC, a partir de su experiencia personal.[cite: 21]\tLL.4.5.4.\tLL.4.5.4. Componer textos creativos que adapten o combinen diversas estructuras y recursos literarios.[cite: 21]\tI.LL.4.9.1.\tI.LL.4.9.1. Compone y recrea textos literarios que adaptan o combinan diversas estructuras y recursos, expresando intenciones determinadas (ironía, sarcasmo, humor, etc.) mediante el uso creativo del significado de las palabras y el uso colaborativo de diversos medios y recursos de las TIC. (I.3.,I4)[cite: 21]\t\t\tNO
Lengua y Literatura\tEGB Superior\tCE.LL.4.9.\tCE.LL.4.9. Compone y recrea textos literarios que adaptan o combinan diversas estructuras y recursos literarios, expresa intenciones determinadas (ironía, sarcasmo, humor, etc.) mediante el uso creativo del significado de las palabras, la utilización colaborativa de diversos medios y recursos de las TIC, a partir de su experiencia personal.[cite: 21]\tLL.4.5.6.\tLL.4.5.6. Recrear textos literarios leídos o escuchados con el uso colaborativo de diversos medios y recursos de las TIC.[cite: 21]\tI.LL.4.9.1.\tI.LL.4.9.1. Compone y recrea textos literarios que adaptan o combinan diversas estructuras y recursos, expresando intenciones determinadas (ironía, sarcasmo, humor, etc.) mediante el uso creativo del significado de las palabras y el uso colaborativo de diversos medios y recursos de las TIC. (I.3.,I4)[cite: 21]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.1.\tCE.CN.4.1. Explica a partir de la indagación y exploración el nivel de complejidad de los seres vivos, a partir del análisis de sus propiedades, niveles de organización, diversidad y la clasificación de grupos taxonómicos dados.[cite: 23]\tCN.4.1.1.\tCN.4.1.1. Indagar y explicar las propiedades de los seres vivos e inferir su importancia para el mantenimiento de la vida en la Tierra.[cite: 23]\tI.CN.4.1.1.\tI.CN.4.1.1. Analiza el nivel de complejidad de la materia viva y los organismos, en función de sus propiedades y niveles de organización. (J.3.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.1.\tCE.CN.4.1. Explica a partir de la indagación y exploración el nivel de complejidad de los seres vivos, a partir del análisis de sus propiedades, niveles de organización, diversidad y la clasificación de grupos taxonómicos dados.[cite: 23]\tCN.4.1.2.\tCN.4.1.2. Explorar e identificar los niveles de organización de la materia viva, de acuerdo al nivel de complejidad.[cite: 23]\tI.CN.4.1.1.\tI.CN.4.1.1. Analiza el nivel de complejidad de la materia viva y los organismos, en función de sus propiedades y niveles de organización. (J.3.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.1.\tCE.CN.4.1. Explica a partir de la indagación y exploración el nivel de complejidad de los seres vivos, a partir del análisis de sus propiedades, niveles de organización, diversidad y la clasificación de grupos taxonómicos dados.[cite: 23]\tCN.4.1.7.\tCN.4.1.7. Analizar los niveles de organización y diversidad de los seres vivos y clasificarlos en grupos taxonómicos, de acuerdo con las características observadas a simple vista y las invisibles para el ojo humano.[cite: 23]\tI.CN.4.1.2.\tI.CN.4.1.2. Clasifica seres vivos según criterios taxonómicos dados (dominio y reino) y establece relación entre el grupo taxonómico y los niveles de organización que presenta y su diversidad. (J.3., I.2.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.2.\tCE.CN.4.2. Ejemplifica la complejidad de los seres vivos (animales y vegetales) a partir de la diferenciación de células y tejidos que los conforman, la importancia del ciclo celular que desarrollan, los tipos de reproducción que ejecutan e identifica el aporte de la tecnología para el desarrollo de la ciencia.[cite: 23]\tCN.4.1.3.\tCN.4.1.3. Indagar, con uso del microscopio, de las TIC u otros recursos, y describir las características estructurales y funcionales de las células, y clasificarlas por su grado de complejidad, nutrición, tamaño y forma.[cite: 23]\tI.CN.4.2.1.\tI.CN.4.2.1. Determina la complejidad de las células en función de sus características estructurales, funcionales y tipos e identifica las herramientas tecnológicas que contribuyen al conocimiento de la citología. (J.3., I.2.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.2.\tCE.CN.4.2. Ejemplifica la complejidad de los seres vivos (animales y vegetales) a partir de la diferenciación de células y tejidos que los conforman, la importancia del ciclo celular que desarrollan, los tipos de reproducción que ejecutan e identifica el aporte de la tecnología para el desarrollo de la ciencia.[cite: 23]\tCN.4.1.4.\tCN.4.1.4. Describir, con apoyo de modelos, la estructura de las células animales y vegetales, reconocer sus diferencias y explicar las características, funciones e importancia de los organelos.[cite: 23]\tI.CN.4.2.1.\tI.CN.4.2.1. Determina la complejidad de las células en función de sus características estructurales, funcionales y tipos e identifica las herramientas tecnológicas que contribuyen al conocimiento de la citología. (J.3., I.2.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.2.\tCE.CN.4.2. Ejemplifica la complejidad de los seres vivos (animales y vegetales) a partir de la diferenciación de células y tejidos que los conforman, la importancia del ciclo celular que desarrollan, los tipos de reproducción que ejecutan e identifica el aporte de la tecnología para el desarrollo de la ciencia.[cite: 23]\tCN.4.1.5.\tCN.4.1.5. Diseñar y ejecutar una indagación experimental y explicar las clases de tejidos animales y vegetales, diferenciándolos por sus características, funciones y ubicación.[cite: 23]\tI.CN.4.2.2.\tI.CN.4.2.2. Diferencia las clases de tejidos, animales y vegetales, de acuerdo a características, funciones y ubicación e identifica la contribución del microscopio para el desarrollo de la histología. (J.3., I.2.)[cite: 23]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.3.\tCE.CN.4.3. Diseña modelos representativos sobre la relación que encuentra entre la conformación y funcionamiento de cadenas, redes y pirámides alimenticias, el desarrollo de ciclos de los bioelementos (carbono, oxígeno, nitrógeno), con el flujo de energía al interior de un ecosistema (acuático o terrestre)...[cite: 24]\tCN.4.1.10.\tCN.4.1.10. Observar y explicar en diferentes ecosistemas las cadenas, redes y pirámides alimenticias, identificar los organismos productores, consumidores y descomponedores y analizar los efectos de la actividad humana sobre las redes alimenticias.[cite: 24]\tI.CN.4.3.1.\tI.CN.4.3.1. Elabora la representación de una red alimenticia (por ejemplo, el manglar) en la que se identifican cadenas alimenticias conformadas por organismos productores, consumidores y descomponedores. (J.3., J.4.)[cite: 24]\t\t\tNO
Ciencias Naturales\tEGB Superior\tCE.CN.4.3.\tCE.CN.4.3. Diseña modelos representativos sobre la relación que encuentra entre la conformación y funcionamiento de cadenas, redes y pirámides alimenticias, el desarrollo de ciclos de los bioelementos (carbono, oxígeno, nitrógeno), con el flujo de energía al interior de un ecosistema (acuático o terrestre)...[cite: 24]\tCN.4.1.11.\tCN.4.1.11. Diseñar modelos representativos del flujo de energía en cadenas y redes alimenticias, explicar y demostrar el rol de los seres vivos en la trasmisión de energía en los diferentes niveles tróficos.[cite: 24]\tI.CN.4.3.2.\tI.CN.4.3.2. Relaciona el desarrollo de los ciclos de carbono, oxígeno y nitrógeno con el flujo de energía como mecanismo de reciclaje de estos elementos, y el funcionamiento de las cadenas tróficas en los ecosistemas. (J.3., J.1.)[cite: 24]\t\t\tNO
Ciencias Sociales\tEGB Superior\tCE.CS.4.1.\tCE.CS.4.1. Analiza y utiliza los conceptos de “historia y trabajo”, como herramientas teóricas en función de comprender el proceso de producción y reproducción de la cultura material y simbólica de los pueblos americanos y de la humanidad, destacando el protagonismo de la mujer en su evolución.[cite: 35]\tCS.4.1.1.\tCS.4.1.1. Reconocer el estudio de la Historia como conocimiento esencial para entender nuestro pasado y nuestra identidad y para comprender cómo influyen en el mundo en que vivimos.[cite: 35]\tI.CS.4.1.1.\tI.CS.4.1.1. Explica la importancia de la historia para la comprensión del origen de la humanidad, del trabajo como factor fundamental de la evolución y desarrollo de una sociedad, el papel de la mujer en la invención de la agricultura y la influencia de la agricultura y de la escritura en las formas de vida y organización social de los pueblos. (I.2.)[cite: 35]\t\t\tNO
Ciencias Sociales\tEGB Superior\tCE.CS.4.1.\tCE.CS.4.1. Analiza y utiliza los conceptos de “historia y trabajo”, como herramientas teóricas en función de comprender el proceso de producción y reproducción de la cultura material y simbólica de los pueblos americanos y de la humanidad, destacando el protagonismo de la mujer en su evolución.[cite: 35]\tCS.4.1.2.\tCS.4.1.2. Describir el origen de la humanidad en África y su difusión a los cinco continentes, con base en el trabajo y su capacidad de adaptación a diversos ambientes y situaciones climáticas.[cite: 35]\tI.CS.4.1.1.\tI.CS.4.1.1. Explica la importancia de la historia para la comprensión del origen de la humanidad, del trabajo como factor fundamental de la evolución y desarrollo de una sociedad, el papel de la mujer en la invención de la agricultura y la influencia de la agricultura y de la escritura en las formas de vida y organización social de los pueblos. (I.2.)[cite: 35]\t\t\tNO
Ciencias Sociales\tEGB Superior\tCE.CS.4.1.\tCE.CS.4.1. Analiza y utiliza los conceptos de “historia y trabajo”, como herramientas teóricas en función de comprender el proceso de producción y reproducción de la cultura material y simbólica de los pueblos americanos y de la humanidad, destacando el protagonismo de la mujer en su evolución.[cite: 35]\tCS.4.1.16.\tCS.4.1.16. Analizar el origen de los primeros pobladores de América y sus formas de supervivencia, con base en las evidencias materiales que se han descubierto.[cite: 35]\tI.CS.4.1.2.\tI.CS.4.1.2. Analiza la evolución y relación entre el origen de los primeros pobladores de América, la formación de grandes civilizaciones, el desarrollo de las culturas andinas, el origen y desarrollo del Imperio inca y la estructura organizativa del Tahuantinsuyo, destacando el legado material y cultural indígena y los rasgos más significativos que diferencian las culturas americanas. (I.2.)[cite: 35]\t\t\tNO
Ciencias Sociales\tEGB Superior\tCE.CS.4.2.\tCE.CS.4.2. Analiza el origen de las sociedades divididas en clases en el mundo (esclavitud, pobreza), en función de los acontecimientos históricos de colonización y conquista (conquista del Imperio Romano, conquista del Imperio Inca, conquista europea en América) y la supervivencia de estructuras de desigualdad.[cite: 36]\tCS.4.1.5.\tCS.4.1.5. Identificar los grandes Imperios esclavistas de la Antigüedad en el Oriente Medio, destacando el rol de la agricultura, la escritura y los ejércitos.[cite: 36]\tI.CS.4.2.1.\tI.CS.4.2.1. Compara los Imperios esclavistas de la Antigüedad en el Oriente Medio con el Imperio romano, los Imperios asiáticos (China e India), reconociendo que las estructuras de desigualdad son semejantes en diversos momentos históricos y el impacto del surgimiento del Islam en Arabia y su difusión al norte de África. (I.2.)[cite: 36]\t\t\tNO
Ciencias Sociales\tEGB Superior\tCE.CS.4.3.\tCE.CS.4.3. Examina las diferentes formas de conciencia e insurgencia social (cristianismo humanismo, revoluciones, etc.) como expresiones y representaciones del poder en el contexto del paso de la antigüedad al feudalismo y al capitalismo y el desarrollo de la modernidad, con sus transformaciones económicas, sociales, políticas e ideológicas en el mundo y América Latina.[cite: 37]\tCS.4.1.7.\tCS.4.1.7. Explicar la naturaleza de las culturas mediterráneas, especialmente la griega, con énfasis en su influencia en el pensamiento filosófico y democrático.[cite: 37]\tI.CS.4.3.1.\tI.CS.4.3.1. Examina los orígenes de la conciencia humanista y el cristianismo, y la influencia de las culturas mediterráneas en el pensamiento filosófico y democrático, como antecedente para la tolerancia y la diversidad religiosa. (I.2.)[cite: 37]\t\t\tNO
Matemática\tEGB Superior\tCE.M.4.1.\tCE.M.4.1. Emplea las relaciones de orden, las propiedades algebraicas (adición y multiplicación), las operaciones con distintos tipos de números (Z, Q, I) y expresiones algebraicas, para afrontar inecuaciones y ecuaciones con soluciones de diferentes campos numéricos, y resolver problemas de la vida real, seleccionando la forma de cálculo apropiada e interpretando y juzgando las soluciones obtenidas dentro del contexto del problema; analiza la necesidad del uso de la tecnología.[cite: 58]\tM.4.1.1.\tM.4.1.1. Reconocer los elementos del conjunto de números enteros Z, ejemplificando situaciones reales en las que se utilizan los números enteros negativos.[cite: 58]\tRef.I.M.4.1.1.\tEjemplifica situaciones reales en las que se utilizan los números enteros; establece relaciones de orden empleando la recta numérica en la solución de expresiones con operaciones combinadas, empleando correctamente la prioridad de las operaciones; juzga la necesidad del uso de la tecnología. (Ref.I.M.4.1.1.) (I.4 .)[cite: 58]\t\t\tSI
Matemática\tEGB Superior\tCE.M.4.1.\tCE.M.4.1. Emplea las relaciones de orden, las propiedades algebraicas (adición y multiplicación), las operaciones con distintos tipos de números (Z, Q, I) y expresiones algebraicas, para afrontar inecuaciones y ecuaciones con soluciones de diferentes campos numéricos, y resolver problemas de la vida real, seleccionando la forma de cálculo apropiada e interpretando y juzgando las soluciones obtenidas dentro del contexto del problema; analiza la necesidad del uso de la tecnología.[cite: 58]\tM.4.1.2.\tM.4.1.2. Establecer relaciones de orden en un conjunto de números enteros, utilizando la recta numérica y la simbología matemática (=, ≥).[cite: 58]\tRef.I.M.4.1.1.\tEjemplifica situaciones reales en las que se utilizan los números enteros; establece relaciones de orden empleando la recta numérica en la solución de expresiones con operaciones combinadas, empleando correctamente la prioridad de las operaciones; juzga la necesidad del uso de la tecnología. (Ref.I.M.4.1.1.) (I.4 .)[cite: 58]\t\t\tSI
Matemática\tEGB Superior\tCE.M.4.1.\tCE.M.4.1. Emplea las relaciones de orden, las propiedades algebraicas (adición y multiplicación), las operaciones con distintos tipos de números (Z, Q, I) y expresiones algebraicas, para afrontar inecuaciones y ecuaciones con soluciones de diferentes campos numéricos, y resolver problemas de la vida real, seleccionando la forma de cálculo apropiada e interpretando y juzgando las soluciones obtenidas dentro del contexto del problema; analiza la necesidad del uso de la tecnología.[cite: 58]\tM.4.1.3.\tM.4.1.3. Operar en Z (adición, sustracción, multiplicación) de forma numérica, aplicando el orden de operación.[cite: 58]\tRef.I.M.4.1.1.\tEjemplifica situaciones reales en las que se utilizan los números enteros; establece relaciones de orden empleando la recta numérica en la solución de expresiones con operaciones combinadas, empleando correctamente la prioridad de las operaciones; juzga la necesidad del uso de la tecnología. (Ref.I.M.4.1.1.) (I.4 .)[cite: 58]\t\t\tSI
Matemática\tEGB Superior\tCE.M.4.1.\tCE.M.4.1. Emplea las relaciones de orden, las propiedades algebraicas (adición y multiplicación), las operaciones con distintos tipos de números (Z, Q, I) y expresiones algebraicas, para afrontar inecuaciones y ecuaciones con soluciones de diferentes campos numéricos, y resolver problemas de la vida real, seleccionando la forma de cálculo apropiada e interpretando y juzgando las soluciones obtenidas dentro del contexto del problema; analiza la necesidad del uso de la tecnología.[cite: 58]\tM.4.1.10.\tM.4.1.10. Resolver ecuaciones de primer grado con una incógnita en Z en la solución de problemas.[cite: 58]\tI.M.4.1.2.\tI.M.4.1.2. Formula y resuelve problemas aplicando las propiedades algebraicas de los números enteros y el planteamiento y resolución de ecuaciones e inecuaciones de primer grado con una incógnita; juzga e interpreta las soluciones obtenidas dentro del contexto del problema. (I.2)[cite: 58]\t\t\tNO`;

function cleanText(t: string) {
  if (!t) return "";
  return t.replace(/\[cite:\s*\d+\]/g, "").replace(/\s+/g, " ").trim();
}

const subjectIdMap: Record<string, string> = {
  "Lengua y Literatura": "subj-1790604314566",
  "Ciencias Naturales": "subj-1790608315861",
  "Ciencias Sociales": "subj-1790606203387",
  "Matemática": "subj-1790604133273"
};

async function run() {
  console.log("=== 1. ELIMINANDO REGISTROS VIEJOS/ERRONEOS DE FIRESTORE ===");
  const collections = ['evaluation_criteria', 'dcds', 'evaluation_indicators'];
  for (const colName of collections) {
    const snap = await getDocs(collection(db, colName));
    console.log(`Borrando ${snap.size} documentos en ${colName}...`);
    const docIds = snap.docs.map(d => d.id);
    for (let i = 0; i < docIds.length; i += 400) {
      const chunk = docIds.slice(i, i + 400);
      const batch = writeBatch(db);
      chunk.forEach(id => batch.delete(doc(db, colName, id)));
      await batch.commit();
    }
  }

  console.log("=== 2. PROCESANDO TABLA DEFINITIVA DEL USUARIO ===");
  const lines = rawTable.trim().split("\n");
  const criteriaMap = new Map();
  const dcdList: any[] = [];
  const ieMap = new Map();

  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split("\t");
    const [asignaturaRaw, subnivelRaw, ceCodeRaw, ceDescRaw, dcdCodeRaw, dcdDescRaw, ieCodeRaw, ieDescRaw, compRaw, insRaw, desagregadaRaw] = parts;

    const asignatura = cleanText(asignaturaRaw);
    const subnivel = cleanText(subnivelRaw) || "EGB Superior";
    const ceCode = cleanText(ceCodeRaw);
    const ceDesc = cleanText(ceDescRaw);
    const dcdCode = cleanText(dcdCodeRaw);
    const dcdDesc = cleanText(dcdDescRaw);
    const ieCode = cleanText(ieCodeRaw);
    const ieDesc = cleanText(ieDescRaw);
    const ins = cleanText(insRaw);
    const isDisaggregated = cleanText(desagregadaRaw).toUpperCase() === "SI";
    const subjectId = subjectIdMap[asignatura] || "subj-1790604314566";

    const critId = `ce-${ceCode.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase().replace(/-+$/, "")}`;

    if (!criteriaMap.has(ceCode)) {
      criteriaMap.set(ceCode, {
        id: critId,
        code: ceCode,
        description: ceDesc,
        subjectId,
        gradeLevel: subnivel,
        institutionId: "none"
      });
    }

    dcdList.push({
      id: `dcd-${dcdCode.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase().replace(/-+$/, "")}`,
      code: dcdCode,
      description: dcdDesc,
      subjectId,
      gradeLevel: subnivel,
      criterionId: critId,
      isDisaggregated,
      curricularInsertions: ins ? [ins] : undefined,
      institutionId: "none"
    });

    const ieKey = `${ceCode}_${ieCode}`;
    if (!ieMap.has(ieKey)) {
      ieMap.set(ieKey, {
        id: `ie-${ieKey.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase().replace(/-+$/, "")}`,
        code: ieCode,
        description: ieDesc,
        criterionId: critId,
        institutionId: "none"
      });
    }
  }

  const criteriaArray = Array.from(criteriaMap.values());
  const indicatorsArray = Array.from(ieMap.values());

  console.log(`Guardando ${criteriaArray.length} Criterios en Firestore...`);
  const b1 = writeBatch(db);
  criteriaArray.forEach(c => b1.set(doc(db, 'evaluation_criteria', c.id), c));
  await b1.commit();

  console.log(`Guardando ${dcdList.length} DCDs en Firestore...`);
  const b2 = writeBatch(db);
  dcdList.forEach(d => {
    const data: any = { ...d };
    if (!data.curricularInsertions) delete data.curricularInsertions;
    b2.set(doc(db, 'dcds', d.id), data);
  });
  await b2.commit();

  console.log(`Guardando ${indicatorsArray.length} Indicadores en Firestore...`);
  const b3 = writeBatch(db);
  indicatorsArray.forEach(i => b3.set(doc(db, 'evaluation_indicators', i.id), i));
  await b3.commit();

  console.log("=== 3. VERIFICACION FINAL ===");
  const ceSnap = await getDocs(collection(db, 'evaluation_criteria'));
  const dcdSnap = await getDocs(collection(db, 'dcds'));
  const ieSnap = await getDocs(collection(db, 'evaluation_indicators'));
  console.log(`Final CE count: ${ceSnap.size}`);
  console.log(`Final DCD count: ${dcdSnap.size}`);
  console.log(`Final IE count: ${ieSnap.size}`);

  process.exit(0);
}

run().catch(e => {
  console.error(e);
  process.exit(1);
});
